### PR TITLE
fix(mir-importer): type six intrinsic results from the projected destination

### LINKED ISSUE #773: mir-importer: intrinsic sites that type the call result from the bare destination local fail as a verifier type-mismatch on a projected destination
PR #769 taught `store_result_to_place` to write an intrinsic result through a projected call destination (`(*p)`, `x.0`, `x[i]`, `x[0]`) and switched the bitops/saturating/bigint/exact_div sites to type the call result from `Place::ty` via `types::translate_destination_type`. Six sites still type it from `body.locals()[destination.local].ty`, i.e. the bare local:

- `crates/mir-importer/src/translator/terminator/intrinsics/float_math.rs:626` (float-math placeholder calls) and `:497` (tuple-result path, destination tuple type)
- `crates/mir-importer/src/translator/terminator/mod.rs:2637` (`select_unpredictable`)
- `crates/mir-importer/src/translator/terminator/intrinsics/memory.rs:861` and `:954` (`DynamicSharedArray::get`/`offset` pointee extraction from the destination type)
- `crates/mir-importer/src/translator/terminator/intrinsics/generated.rs:22382` (`elect_sync` tuple destination; the template that emits it is `crates/cuda-intrinsics-gen/src/render.rs:10976`)

With a projected destination (custom MIR only, e.g. `RET.1 = powf(...)`), the call op is created with the whole aggregate's type (or the pointer's type for `(*p)`), and `store_result_to_place` then stores that mistyped value through the correctly typed projected address. The pipeline dies as a MirStoreOp verifier type-mismatch ("Compilation error: invalid input program.") instead of either a correct store or the clean "unsupported construct" diagnostic the four fixed sites now guarantee.

Fix: switch each site to `types::translate_destination_type(ctx, body, destination, &loc)`; for generated.rs update the render.rs template and regenerate. The two memory.rs sites match on the destination's `RawPtr` kind to extract a pointee, so they want the projected `Place::ty` before that match rather than the local's type. Add custom-MIR coverage alongside the `mir_projected_call_destination` example or as importer unit tests.

Severity: low (reachable only from `#[custom_mir]`), but the failure mode is a confusing verifier error rather than a diagnostic.

### PR DESCRIPTION
**Pull request by vyncint**
Closes #773.

#769 taught `store_result_to_place` to write an intrinsic result through a
projected call destination and switched four sites to type the result from
`Place::ty`. The six you enumerated still typed it from
`body.locals()[destination.local].ty`, so with a projected destination the call
op got the whole aggregate's type (or the pointer's, for `(*p)`) and the store
then pushed that mistyped value through a correctly typed address.

All six converted, matching the four already fixed:

| site | intrinsic |
|---|---|
| `float_math.rs` | placeholder calls, and the `sincos` tuple-result path |
| `terminator/mod.rs` | `select_unpredictable` |
| `memory.rs` (x2) | `DynamicSharedArray::get` / `::offset` |
| `generated.rs` | `elect_sync`, via the `render.rs` template |

The two `memory.rs` sites match on the destination's `RawPtr` kind to pull out a
pointee, so as you noted they want the projected **rustc** type rather than the
dialect one — they take `destination.ty(body.locals())` before the match, with
the same diagnostic `translate_destination_type` emits when a place cannot be
resolved. The `generated.rs` hunk is regeneration output rather than a hand
edit; `cargo run -p cuda-intrinsics-gen -- check` passes.

## No test, deliberately

I tried to build a `#[custom_mir]` reproducer for the `select_unpredictable`
site — `RET.1 = select_unpredictable(..)` on a `(u64, u32)` — and **could not
make it fail on `main`**:

* with a literal condition, rustc folds the call before the importer sees it;
* with the condition derived from an earlier custom-MIR result, it compiles
  clean both before and after.

A case that passes either way would sit in the suite guarding nothing, so I left
it out rather than claim coverage it does not provide. If you know a shape that
does reach these six with a projection, I am happy to add it — the four
`bitops`/`saturating`/`bigint`/`exact_div` sites presumably had one.

Gates: `cargo fmt --check`, `clippy --all-targets -D warnings`, and
`-p mir-importer -p cuda-intrinsics-gen -p mir-lower` unit tests (930 / 288 /
182 / 102, all green). No GPU needed — this is importer typing only.

## Merge order

#770 and #721 both regenerate `generated.rs` (they add intrinsics). Neither
touches the typing pattern, so there is no semantic conflict, but whichever
lands last will collide textually in that file. If this goes second, the fix is
just `cargo run -p cuda-intrinsics-gen -- generate` on top — happy to rebase.

## Aside, possibly worth its own issue

While probing, `core::hint::black_box` failed device codegen outright:

```
Translation failed: ...core/src/hint.rs: line: 491 Compilation error: invalid input program.
```

That is unrelated to this change and I have not investigated it; flagging it in
case it is news.

### CODE REVIEW

**Comment by nihalpasham** [comment]
The typing fix is right; 

**I added the following:**
- completed the other half at 3 sites (`sincos`, `fn-item`, `closure`) where the result was typed from the projection but still stored to the bare local, and 
- added four optimizer-proof regression cases to the example (they hard-fail the build on main's importer and pass here on sm_120). 

Merging, 

closes #773.

**Comment by nihalpasham** [comment]
Thanks @vyncint! The six-site typing fix is right; we completed the other half at three sites (sincos, function-item, closure) where the result was typed from the projection but still stored to the bare local, and added four optimizer-proof regression cases to the example (they hard-fail the device build on main's importer and pass here on sm_120). Merging, closes #773.

**Review by nihalpasham — APPROVED** [review]
